"openapi": "3.0.0,"
"info": {
  "description": "Clinical Trial API for the EU Portal and Database"
  "version": "3.0.0-oas3"
"title": "CTIS - ClinicalTrial API"
}
"paths":
  "/":
    "get":
      "tags":
        - Clinical Trials
      "summary": "Get a list of all clinical trials you are allowed to see"
      "description": "''"
      "operationId": "getClinicalTrials"
      "responses":
        "'200'":
          "description": "successful operation"
          "content":
            "application/xml":
              "schema":
                "$ref": "'#/components/schemas/messageType'"
"servers":
  - "url": ""https"://virtserver.swaggerhub.com/sostma/CT-ClinicalTrials-API/1.0.0"
"components":
  "schemas":
    "partyType":
      "description": "Parter i kommunikationen ”LV”, ”EPM”, ”RBC”"
      "type": "string"
      "enum":
        - LV
        - EPM
        - RBC
    "messageReasonType":
      "description": "En text som beskriver varför meddelandet skickats."
      "type": "string"
      "enum":
        - "'Notis": "Initial ansökan del I och II'"
        - "'Notis": "Initial ansökan del I'"
        - "'Notis": "Initial ansökan del II'"
        - "'Notis": "Ändringsansökan del I och II'"
        - "'Notis": "Ändringsansökan del I'"
        - "'Notis": "Ändringsansökan del II'"
        - "'Notis": "Valid ansökan'"
        - "'Notis": "Validerings-RFI till sponsor'"
        - "'Begäran": "Preliminär granskning del I'"
        - "'Begäran": "Preliminär granskning del II'"
        - "'Svar": "Preliminär granskning del I'"
        - "'Svar": "Preliminär granskning del II'"
        - "'Begäran": "Granskning av synpunkter från MSC'"
        - "'Svar": "Granskning av synpunkter från MSC'"
        - "'Notis": "Bedömnings-RFI del I till sponsor'"
        - "'Notis": "Bedömnings-RFI del II till sponsor'"
        - "'Begäran": "Yttrande del I'"
        - "'Begäran": "Yttrande del II'"
        - "'Notis": "Komplettering från sponsor del I'"
        - "'Notis": "Komplettering från sponsor del II'"
        - "'Notis": "Synpunkter från MSC efter komplettering del I'"
        - "'Notis": "Synpunkter från MSC efter komplettering del II'"
        - "'Svar": "Yttrande del I'"
        - "'Svar": "Yttrande del II'"
        - "'Notis": "AR och slutsats del I'"
        - "'Notis": "AR och slutsats del II'"
        - 'Notis och "kommentarsmöjlighet": "AR och slutsats del I'"
        - 'Notis och "kommentarsmöjlighet": "AR och slutsats del II'"
        - 'Kommentar på "notis": "Underlag till invändning mot RMS slutsats'"
        - "'Notis": "Ansökan dragits tillbaka'"
        - "'Notis": "Ansökan förfallen'"
        - "'Notis": "Ansökan tyst godkännande'"
        - "'Notis": "Beslut för ansökan'"
        - "'Notis": "Informell RFI del I'"
        - "'Notis": "Informell RFI del II'"
        - "'Notis": "Informell RFI validering'"
        - "'Notis": "Beslut för överflyttad prövningheaderType'"
    "domainType":
      "description": "Anger vilken prövningsdomän ärendet gäller"
      "type": "string"
      "enum":
        - HumMedProd
        - MT
    "headerType":
      "description": "Metadata som beskriver meddelandet självt"
      "type": "object"
      "properties":
        "version":
          "description": "Version för det protokoll som versionen motsvarar."
          "type": "string"
          "enum":
            - 3.0-SNAPSHOT
        "from":
          "$ref": "'#/components/schemas/partyType'"
        "to":
          "$ref": "'#/components/schemas/partyType'"
        "transactionId":
          "description": "Ett unikt id för meddelandet. Återanvänds inte även om meddelandet skickas om."
          "type": "string"
        "messageId":
          "description": "Ett id för meddelandet. Om ett meddelande behöver skickas om används samma messageId som på ursprungsmeddelandet."
          "type": "string"
        "parentMessageId":
          "description": "Används när ett meddelande är ett svar på ett annat meddelande. Sätt då till det värde messageId har i urspungsmeddelandet."
          "type": "string"
        "timestamp":
          "description": "Tidpunkten när meddelandet skapas uttryckt enligt ISO-8601 med sekundupplösning."
          "type": "string"
          "format": "date-time"
        "domain":
          "$ref": "'#/components/schemas/domainType'"
        "messageReason":
          "$ref": "'#/components/schemas/messageReasonType'"
        "dueDate":
          "description": "Senaste datumet när avsändaren vill ha svar, uttryckt enligtISO-8601 med datumupplösning. Null om inget svar förväntas."
          "type": "string"
          "format": "date"
      "required":
        - version
        - from
        - to
        - transactionId
        - messageId
        - timestamp
        - messageReason
    "addressType":
      "type": "object"
      "properties":
        "addressLine1":
          "description": "Adressrad 1"
          "type": "string"
        "addressLine2":
          "description": "Adressrad 2"
          "type": "string"
        "addressLine3":
          "description": "Adressrad 3"
          "type": "string"
        "addressLine4":
          "description": "Adressrad 4"
          "type": "string"
        "postalCode":
          "description": "Postnummer"
          "type": "string"
        "city":
          "description": "Ort"
          "type": "string"
    "principalInvestigatorType":
      "description": "Prövningsställets huvudprövares kontaktuppgifter."
      "type": "object"
      "properties":
        "familyName":
          "description": "Efternamn"
          "type": "string"
        "givenName":
          "description": "Förnamn"
          "type": "string"
        "phoneNumber":
          "description": "Telefonnummer"
          "type": "string"
        "emailAddress":
          "description": "E-postadress"
          "type": "string"
    "trialSiteType":
      "type": "object"
      "properties":
        "trialSiteName":
          "description": "Namnet på prövningsstället. Värdet kommer tillsvidare alltid vara null eftersom det är så det skickas ut från CTIS."
          "type": "string"
        "department":
          "description": "Ett fritextfält"
          "type": "string"
        "organisationAddress":
          "$ref": "'#/components/schemas/addressType'"
        "principalInvestigator":
          "$ref": "'#/components/schemas/principalInvestigatorType'"
    "part2Type":
      "description": "Huvudobjekt för data om prövningen som bara berör Sverige."
      "type": "object"
      "properties":
        "trialSites":
          "type": "array"
          "items":
            "$ref": "'#/components/schemas/trialSiteType'"
    "clinicalTrialType":
      "description": "Innehåller vissa översiktsdata om prövningen. Domain=HumMedProd"
      "type": "object"
      "properties":
        "clinicalTrialId":
          "description": "Prövningens id i CTIS-portalen"
          "type": "string"
        "title":
          "description": "Prövningens officiella titel"
          "type": "string"
        "emaSubmissionDate":
          "type": "string"
          "format": "date"
        "swedenRole":
          "description": "Sveriges aktuella RMS/MSC-status i prövningen. Kan uppdateras under valideringsfasen."
          "type": "string"
          "enum":
            - Föreslagen MSC
            - Föreslagen RMS
            - MSC
            - RMS
        "memberstateConcerned":
          "description": "En lista på alla deltagande länder i prövningen."
          "type": "array"
          "items":
            "type": "string"
          "minItems": "1"
          "uniqueItems": "true"
        "sponsor":
          "type": "object"
          "properties":
            "name":
              "description": "Huvudsponsorns namn baserat på vad som angivits i CTIS-portalen"
              "type": "string"
            "country":
              "description": "Sponsors ort som angivits i adressen."
              "type": "string"
        "part1Data":
          "description": "Huvudobjekt för detaljerade data om prövningen gemensam för alla MSC."
          "type": "object"
          "properties": "{}"
        "swedishPart2Data":
          "$ref": "'#/components/schemas/part2Type'"
    "clinicalStudyType":
      "description": "Innehåller vissa översiktsdata om MT-prövningar. Används tillsammans medDomain=MT"
      "type": "object"
      "properties":
        "cid":
          "description": "Prövningens id i etjänsten för MT-prävningar"
          "type": "string"
        "title":
          "description": "Prövningens titel"
          "type": "string"
        "submissionDate":
          "description": "Datum då ansökan skickades in till ctis-portalen."
          "type": "string"
          "format": "date"
        "sponsor":
          "type": "object"
          "properties":
            "name":
              "description": "Huvudsponsorns namn baserat på vad som angivits i ansökningsformuläret"
              "type": "string"
    "documentTypeType":
      "description": "Benämning på dokumentet i CTIS-portalen. Alla dokument CTIS-portalenär hårt typade och representeras av en kod och ett “DisplayName”. Ensponsor kan inte lägga till godtyckliga dokument, men kan lägga till flera dokument av varje tillåten typ."
      "type": "object"
      "properties":
        "code":
          "description": "Dokumenttypens kod"
          "type": "string"
        "displayName":
          "description": "displayName uttrycks på svenska och kan användas för att beskrivabilagorna för handläggarna. Mängden av dokumenttyper som finnstillgängliga är inte bunden utan kan utökas efter hand."
          "type": "string"
      "required":
        - code
        - displayName
    "documentInListType":
      "type": "object"
      "properties":
        "filename":
          "description": "Filnamnet på dokumentet"
          "type": "string"
        "applicationPart":
          "description": "Om dokumentet tillhör del I eller del II, representerad som ”1”eller ”2”. Observera att även ”” förekommer, vilket är rapporteratsom bug hos CTIS/EMA."
          "type": "string"
        "systemVersion":
          "description": "Version som uppdateras varje gång dokumentet laddas upp iCTIS-portalen"
          "type": "string"
        "documentType":
          "$ref": "'#/components/schemas/documentTypeType'"
      "required":
        - filename
        - documentType
    "sponsorDocumentsType":
      "description": "Lista på metadata om dokument från prövningens sponsor"
      "type": "array"
      "items":
        "$ref": "'#/components/schemas/documentInListType'"
    "otherDocumentsType":
      "description": "Lista med metadata om samverkansdokument som finns i meddelandet. Skalli samtliga fall vara minst 4 stycken, message.json, message.htm,ctisMetadata.json och ctismetadata.htm"
      "type": "array"
      "items":
        "allOf":
          - "$ref": "'#/components/schemas/documentInListType'"
          - "description": "Struktur för beskrivningen av bifogade samverkansdokument."
          - "minItems": "4"


    "caseClassType":
      "description": "Den klassificering ärende har i LVs klassificeringssystem LVKS"
      "type": "string"
      "enum":
        - Nyansökan
        - Ändring
    "decisionType":
      "description": "I fall där det finns ett beslut är utfallet noterat i detta element."
      "type": "string"
      "enum":
        - Avslag
        - Avslut
        - Bifall
        - Avvisning
        - Avskrivning
    "decisionDetailType":
      "description": "Ytterligare information om beslutet som fattats, i princip om det finns villkor alternativt motiv till avslag."
      "oneOf":
        - "type": "string"
          "enum":
            - Bifall enligt ansökan i sin helhet
            - Förutsättningar att bevilja ansökan saknas
            - Nödvändig komplettering inte inkommen
            - Ingen ytterligare åtgärd krävs
            - Ansökan ej komplett eller annan formell brist
            - Ansökan återtagen
        - {}
    "timeTableType":
      "description": "Avgränsad aktivitet i handläggningen av en ansökan om prövningstillstånd för farmakologisk prövning."
      "required":
        - activity
        - order
      "type": "object"
      "properties":
        "activity":
          "description": ""LV":s beskrivande text av tidtabellhändelsen"
          "type": "string"
        "activityType":
          "description": ""LV":s interna typ på tidtabellhändelsen. Exempelvis start, deadline eller meeting."
          "type": "string"
        "status":
          "oneOf":
            - "type": "string"
              "enum":
                - Selected
                - Ongoing
                - Completed
            - {}
        "key":
          "description": "En nyckel till tidtabellshändelsen i "LV":särendehanteringssystem."
          "type": "string"
        "order":
          "description": "Sorteringsordning av tidtabellhändelserna. I dokumentet kan händelserna komma osorterade."
          "type": "integer"
        "plannedEndDate":
          "description": "Det planerade datumet då tidtabellhändelsen ska avslutas, uttryckt enligt ISO-8601 med datumupplösning."
          "type": "string"
          "format": "date"
        "actualEndDate":
          "description": "Det datum då tidtabellhändelsen faktiskt avslutades, uttryckt enligt ISO-8601 med datumupplösning."
          "type": "string"
          "format": "date"
    "kpCaseDataType":
      "description": "Metadata gällande KP-ärendet och dess behandling"
      "type": "object"
      "properties":
        "lvDiaryNumber":
          "description": "Diarienummer från LV, unikt ID för varje ansökan. Används som korrelationsID för olika meddelanden i ett ärende."
          "type": "string"
        "caseClass":
          "$ref": "'#/components/schemas/caseClassType'"
        "caseType":
          "description": "Den ärendetyp som LV gett ärendet. Ska ge EPM/RBC tillräcklig information om vilken sorts ärende det är frågan om (multinationell eller bara Sverige? Del I, del II, eller båda? Nyansökan eller ändringsansökan?)"
          "type": "string"
          "enum":
            - 'KP-ansökan, multinationell, initialt del I'
            - 'KP-ansökan, multinationell, initialt komplett'
            - 'KP-ansökan, multinationell, transitional'
            - 'KP-ansökan, mononationell, initialt del I'
            - 'KP-ansökan, mononationell, initialt komplett'
            - 'KP-ansökan, mononationell, transitional'
            - 'KP-ansökan, Tillägg av SE som MSC'
            - 'Ändring, multinationell, del I'
            - 'Ändring, multinationell, del I och del II'
            - 'Ändring, mononationell, del I'
            - 'Ändring, mononationell, del I och del II'
            - 'Ändring, nationell, del II'
        "isTransitioned":
          "description": "Boolean som ger true om ärendet gäller en prövning som flyttats över från gamla reglementet. Finns bara med för det ärende som flyttar över prövningen, inte för efterkommande ändringsansökningar på den nyskapade kliniska prövningen"
          "type": "boolean"
        "transitionedFrom":
          "description": "EudtraCT-nummer på den tidigare prövningen.Finns bara med för det ärende som flyttar över prövningen, inte för efterkommande ändringsansökningar på den nyskapade kliniska prövningen"
          "type": "string"
        "decision":
          "$ref": "'#/components/schemas/decisionType'"
        "decisionDetail":
          "$ref": "'#/components/schemas/decisionDetailType'"
        "concernsEpm":
          "description": "Anger om ansökan rör EPM och RBC. Kan vara null om "EMP:s/RBS":s medverkan inte ännu kunnat bestämmas."
          "type": "boolean"
        "concernsRbc":
          "description": "Anger om ansökan rör EPM och RBC. Kan vara null om "EMP:s/RBS":s medverkan inte ännu kunnat bestämmas."
          "type": "boolean"
        "timetable":
          "description": "Lista på för RBC/EPM relevanta tidtabellshändelser så som LV planerar dem. Ska användas för att RBC/EPM ska kunna planera framtida bemanning."
          "type": "array"
          "items":
            "$ref": "'#/components/schemas/timeTableType'"
      "required":
        - lvDiaryNumber
        - caseType
    "mtCaseDataType":
      "description": "Metadata gällande KP-ärendet och dess behandling"
      "type": "object"
      "properties":
        "lvDiaryNumber":
          "description": "Diarienummer från LV, unikt ID för varje ansökan. Används som korrelationsID för olika meddelanden i ett ärende."
          "type": "string"
        "caseClass":
          "$ref": "'#/components/schemas/caseClassType'"
        "caseType":
          "description": "Den ärendetyp som LV gett ärendet. Ska ge EPM/RBC tillräcklig information om vilken sorts ärende det är frågan om (multinationell eller bara Sverige? Del I, del II, eller båda? Nyansökan eller ändringsansökan?)"
          "type": "string"
          "enum":
            - 'MDR, Ansökan, 70.7a'
            - 'MDR, Ansökan, 70.7b'
            - 'MDR, Anmälan, 82/74.1'
            - 'IVDR, Ansökan 66.7a'
            - 'IVDR, Ansökan 66.7b'
            - 'IVDR, Anmälan 70.1'
            - 'IVDR, Anmälan 58.2'
            - 'MDR, Ändring av Ansökan, 70.7a'
            - 'MDR, Ändring av Ansökan, 70.7b'
            - 'MDR, Ändring av Anmälan, 74.1'
            - 'MDR, Ändring av Anmälan, 82'
            - 'IVDR, Ändring av Ansökan, 66.7a'
            - 'IVDR, Ändring av Anmälan 70.1'
        "decision":
          "$ref": "'#/components/schemas/decisionType'"
        "decisionDetail":
          "$ref": "'#/components/schemas/decisionDetailType'"
        "concernsEpm":
          "description": "Anger om ansökan rör EPM och RBC. Kan vara null om "EMP:s/RBS":s medverkan inte ännu kunnat bestämmas."
          "type": "boolean"
        "concernsRbc":
          "description": "Anger om ansökan rör EPM och RBC. Kan vara null om "EMP:s/RBS":s medverkan inte ännu kunnat bestämmas."
          "type": "boolean"
        "timetable":
          "description": "Lista på för RBC/EPM relevanta tidtabellshändelser så som LV planerar dem. Ska användas för att RBC/EPM ska kunna planera framtida bemanning."
          "type": "array"
          "items":
            "$ref": "'#/components/schemas/timeTableType'"
      "required":
        - lvDiaryNumber
        - caseType
    "caseDataType":
      "oneOf":
        - "$ref": "'#/components/schemas/kpCaseDataType'"
        - "$ref": "'#/components/schemas/mtCaseDataType'"
    "trialObjectType":
      "oneOf":
        - "$ref": "'#/components/schemas/clinicalTrialType'"
        - "$ref": "'#/components/schemas/clinicalStudyType'"
    "messageType":
      "description": "Schema for message metadata version 3.0-SNAPSHOT"
      "type": "object"
      "properties":
        "header":
          "$ref": "'#/components/schemas/headerType'"
        "caseData":
          "$ref": "'#/components/schemas/caseDataType'"
        "trialObject":
          "$ref": "'#/components/schemas/trialObjectType'"
        "sponsorDocuments":
          "$ref": "'#/components/schemas/sponsorDocumentsType'"
        "otherDocuments":
          "$ref": "'#/components/schemas/otherDocumentsType'"
